""" Utility functions used across other files. """


import GridPythonModule as gpm
import re


from sage.all import BraidGroup, Link


def all_inc_band_attachments(grid: list[list]):
    """
    Generator to iterate through every possible incoherent band attachment from the
    supplied grid.

    Args:
        grid: a grid in the GridPythonModule format.

    Returns:
        tuple[list[list], int, str]: a grid representing a knot resulting from
        an incoherent band attachment on the input grid; the row or column index
        where the band attachment took place; and either 'r' or 'c'; 'r' if the
        band attachment was performed on a row, and 'c' otherwise.
    """
    grid_num = gpm.grid_number(grid)
    # rows
    for i in range(grid_num):
        shifted = gpm.cyclic_shift(grid, horizontal = 0, vertical = i)
        try:
            out = gpm.uncoherent_bs(shifted, 0, which = 'r')
            out = gpm.cyclic_shift(out, horizontal = 0, vertical = grid_num - i)
            yield (out, i, 'r')
        except:
            continue
    # columns
    for i in range(grid_num):
        shifted = gpm.cyclic_shift(grid, horizontal = i, vertical = 0)
        try:
            out = gpm.uncoherent_bs(shifted, 0, which = 'c')
            out = gpm.cyclic_shift(out, horizontal = grid_num - i, vertical = 0)
            yield (out, i, 'c')
        except:
            continue


def convert_to_sage(input_grid: list[list[int]]) -> Link:
    """
    Converts a grid in the format used by GridPythonModule into a Sage `Link`.

    Parameters:
        input_grid: a grid to be converted.

    Returns:
        Link: a Sage `Link` representing the same link as input_grid.
    """
    braid_word = gpm.convert_to_braid(input_grid)
    br_ind = max([abs(c) for c in braid_word]) + 1
    BG = BraidGroup(br_ind)
    return Link(BG(braid_word))


def get_knot_id(sage_id: str) -> str:
    """
    Takes in a string of the format generated by calling `str` or `repr` on a
    Sage `FreeKnotInfoMonoidElement`, i.e. the result of calling `get_knotinfo`
    on a `Link`. Then processes the string to produce a knot id of the form 3_1,
    3_1#4_1, 10n_129, etc. Mirrors are marked with 'm', as in 5_2m and 3_1#3_1m,
    which is the connected sum of the trefoil with its mirror.

    Such composite knot ids are dependent on the order in which Sage gives the
    prime components; i.e. both 3_1m#3_1 and 3_1#3_1m could appear, similarly
    3_1#4_1 and 4_1#3_1. The Sage documentation provides no comment on what
    order it prefers, if any.

    The reverse and concordance inverse of prime knots, should they appear, are
    marked 'r' and 'c' respectively, similarly to the mirror.

    If the provided string is "-", it is returned as is.

    Parameters:
        sage_id: the knot id in Sage's format

    Returns:
        str: a string of the format described above.
    """
    out = sage_id

    if out == "-":
        return out

    while '^' in out:
        original = out
        pos = original.find('^')
        i = pos-1
        while original[i] != '[':
            i -= 1
        
        num_left = pos+1
        num_right = pos+1
        while num_right < len(original) and original[num_right].isnumeric():
            num_right += 1
        
        num = int(original[num_left:num_right])
        extras = ""
        while num > 1:
            extras += "*"
            extras += original[i:pos]
            num -= 1
        
        out = original[:pos] + extras + original[num_right:]
    
    if not '*' in out:
        try:
            out = re.findall(r"'K(.+?)'", out)[0]
        except IndexError:
            print(f"Failed to find knot id in string \"{sage_id}\", returning as is\n", end='')
            return sage_id

    else:
        matches = re.findall(r"'K(.+?)'", out)
        out = '#'.join(matches)

    return out